version: "3.8"

services:
  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "catalog-service"
    container_name: "catalog-service"
    networks:
      - polar
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_ENABLED=true
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9999

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    networks:
      - polar
#    ports:
#      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=polardb_catalog

  config-service:
    image: "config-service"
    container_name: "config-service"
    networks:
      - polar
#    ports:
#      - 9999:9999
#    environment:
#      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001

networks:
  polar:
